---
grails:
    plugin:
        springsecurity:
            userLookup:
              userDomainClassName: 'daweb3.User'
              authorityJoinClassName: 'daweb3.UserRole'
            authority:
              className: 'daweb3.Role'
            rejectIfNoRule: true
            fii:
              rejectPublicInvocations: false
            useSecurityEventListener: true
            successHandler:
              defaultTargetUrl: '/'
            useBasicAuth: true
            basic:
              realmName: "DAWEB - DNSCORE"
            filterChain:
              chainMap:
                - pattern: /status/**
                  filters: JOINED_FILTERS, -exceptionTranslationFilter
                - pattern: /delete/**
                  filters: JOINED_FILTERS, -exceptionTranslationFilter
                - pattern: /assets/**
                  filters: none
                - pattern: /**/js/**
                  filters: none
                - pattern: /**/css/**
                  filters: none
                - pattern: /**/images/**   
                  filters: none
                - pattern: /**/favicon.ico 
                  filters: none
                - pattern: /**             
                  filters: JOINED_FILTERS, -basicAuthenticationFilter, -basicExceptionTranslationFilter
            securityConfigType: InterceptUrlMap
            interceptUrlMap: 
             #   {pattern: '/**',               access: ['permitAll']}
              - {pattern: '/', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/index', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/index.gsp', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/**/js/**', access: ['permitAll']}
              - {pattern: '/**/css/**', access: ['permitAll']}
              - {pattern: '/**/images/**', access: ['permitAll']}
              - {pattern: '/**/icons/favicon.ico', access: ['permitAll']}
              - {pattern: '/login/**', access: ['permitAll']}
              - {pattern: '/logout/**', access: ['permitAll']}
              - {pattern: '/contractor/**', access: ['permitAll']}
              - {pattern: '/queueEntry/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/automatedRetrieval/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/object/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/incoming/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/outgoing/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/status/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/delete/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/package/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/info/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/conversionPolicies/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/cbtalk/**', access: ['ROLE_NODEADMIN']}
              - {pattern: '/user/**', access: ['ROLE_PSADMIN']}
              - {pattern: '/userRole/**', access: ['ROLE_PSADMIN']}
              - {pattern: '/role/**', access: ['ROLE_PSADMIN']}
              - {pattern: '/preservationSystem/**', access: ['ROLE_PSADMIN']}
              - {pattern: '/formatMapping/**', access: ['ROLE_PSADMIN']}
              - {pattern: '/cbNode/**', access: ['ROLE_PSADMIN']}
              - {pattern: '/report/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/systemEvent/**', access: ['ROLE_CONTRACTOR']}
              - {pattern: '/statistics/**', access: ['ROLE_CONTRACTOR']}
            
               
---
# nur f√ºr den Start aus der IDE #
server:
  port: 8095
  
---
grails:
    assets:
      bundle: true
      storagePath: $CATALINA_HOME/webapps/daweb3/assets
    profile: web
    codegen:
        defaultPackage: daweb3
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: true         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
            
app.version.buildNumber: 
    
info:
    app:
        name: 'daweb3'
        version: '0.1'
        grailsVersion: '3.2.11'
jms:
    containers:
        standard:
            messageConverter: null
            connectionFactoryBean: jmsConnectionFactory
    adapters:
        standard:
            persistenceInterceptorBean: null

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    activemq:
        brokerUrl: tcp://localhost
        port: 4455
        pooled: true
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
---
grails:
    resources:
        adhoc:
          - {patterns: '/images/*', '/css/*', '/js/*', '/plugins/*' }
    mime:
       # disable:
       #     accept:
       #         header:
       #             userAgents:
       #                 - Gecko
       #                 - WebKit
       #                 - Presto
       #                 - Trident
        files: 
          extension: true
        use: 
          accept: 
            header: true  
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
           # pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
          #  hal:
          #    - application/hal+json
          #    - application/hal+xml
            xml:
              - text/xml
              - application/xml
        extension : true
   # urlmapping:
   #     cache:
   #         maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            code  cs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh: 
                preprocess: true
    scaffolding:
       templates:
           domainSuffix: Instance     
    exceptionresolver:
       params:
            exclude: password
    databinding:
       dateFormats:
          - 'dd.MM.yyyy'
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: true
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
